apiVersion: v1
kind: Secret
metadata:
    name: maestro-webhook
    namespace: metronome
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:60osJnuKxHdwBj8lgZ3KyjdmAxBjBydnhK/AcUZ+rkjz7XQJx+uEMt0P,iv:l0eIzo9koVwpaRb/jU3iFl6B91gu6NRWIpbhmg9jo9Q=,tag:CHoP1iXI2XWq2iVxLkR6Dg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNDlsUWc4eDRPcjJYY0Z0
            L0djZGdOcUJ5SktkazFqYUNEZ1JCaVpQY0NvCjR0eHdrTk1aOHI2eHdRNjNyNVZt
            NVVZWW9uRmQ1dGlWR3hpT1dSUG44NncKLS0tIEJVcktVUWIzNmFxdHJDQ0FiaFh1
            TWpDc3AxQXRnNm1tVU5HeUdMT3hkUFEK61zYlT57osXhBJ4lsKmcWdz3qdf8iPBE
            lrJevCSwH6WlzB3VkfolN22+Mw1UlrjjjYBfjqdOttyJtf7uFVjriQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18qpxpnpjaadz86hw6q89nna0gp02mz3vc2gx24h2nk4s7ws8luwqtmxg7l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-09T04:37:53Z"
    mac: ENC[AES256_GCM,data:0eUT3c6W6JROl3D4RHYpqOP5beyHMy7HAYTdleermAIX20irE8OgdnOxb/92VeiW6u182EwGbjFjWDEHVbb7z/aSPuK4fnPw+wl1Y1+8OmumWTYcZA/IVdg/7O0BGfY/LkpqoPcnoDBi2DPo/Ik9qhgg0nACsu5ccle8OohQVdM=,iv:8PnImnU1Rai2G0m2u4zbFEzjIy8oERT5z/llozhylHs=,tag:0+dcwHjcBWJuWBJjPiIO5g==,type:str]
    version: 3.13.3
