apiVersion: v1
kind: Secret
metadata:
    name: overture-secrets
    namespace: overture
type: Opaque
stringData:
    OVERTURE_API_TOKEN: ENC[AES256_GCM,data:vhUIliXpJOwDFzxN4HH+frSN/F3PGgRn733vtOr6Thkm7S6cr/imyX7U,iv:w3sQ0WNTiJ/Rmy9jQJgaZG9cvAI5wJzU+vPoNJoUReg=,tag:a9opnIJE9g9K9rv/L9B1gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UXZVaWhMbGh0ZGtpSUhT
            NStCYkhjM2dZVStOYTZyYmZNVHNMdHFXTENBCmxhVFVBZjJzZTJXOURXSmVsbVFp
            Rm5ldEpTMGxhT2xRS1g0U2tTbTNzR0EKLS0tIE5MSzA0K1AveHdRMXowSHlrazZI
            aUxCZmNadDhHUXBUYitvNFhmTmhWclEKW2F7a5ZE513U6bId3ubiu+DJGnT8ta2v
            kX4BMyVgwyHho2QkwfDgnnB2aXA4XAnIuOHciSvX7ZcJ/0J/IBnFDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18qpxpnpjaadz86hw6q89nna0gp02mz3vc2gx24h2nk4s7ws8luwqtmxg7l
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-08T21:48:18Z"
    mac: ENC[AES256_GCM,data:chtkwiOtqpYEChGR1cP2Pc5TYqBDcdPZbnx3ifY3riZ4hAyzxs+dG+yZ9miMuhJYrI05swtWXh3wuInsHOacEV2xkljZTuouy19D7C0KSDgrNU/EmmGpkvu8ncMGWuQ6H1S3SkI5aU/z4OjygFlZqMjMUcCApYeBYOFMZkho/mw=,iv:lfGBPHcAMkrlNIsWTF3f1iQaW8DIeSgGPYlrWwe04lc=,tag:JnZSJmNn4VKRQTTvy8KXog==,type:str]
    version: 3.13.3
